repos:
  - repo: local
    hooks:
      - id: pulumi-aviatrix-demo-go-complete
        name: Pulumi Aviatrix Demo - Go (133 Resources + 23 Data Sources)
        entry: bash -c 'cd /root/GolandProjects/pulumi-avx-test-dummy && go run demo_complete_go.go'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: pulumi-aviatrix-demo-python-complete
        name: Pulumi Aviatrix Demo - Python (133 Resources + 23 Data Sources)
        entry: bash -c 'cd /root/GolandProjects/pulumi-avx-test-dummy && python3 demo_complete_python.py'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: pulumi-aviatrix-demo-csharp-complete
        name: Pulumi Aviatrix Demo - C# (133 Resources + 23 Data Sources)
        entry: bash -c 'cd /root/GolandProjects/pulumi-avx-test-dummy && cd csharp-demo && dotnet run'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: pulumi-aviatrix-demo-java-complete
        name: Pulumi Aviatrix Demo - Java (133 Resources + 23 Data Sources)
        entry: bash -c 'cd /root/GolandProjects/pulumi-avx-test-dummy && javac demo_complete_java.java && java DemoCompleteJava'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: pulumi-aviatrix-demo-typescript-complete
        name: Pulumi Aviatrix Demo - TypeScript (133 Resources + 23 Data Sources)
        entry: bash -c 'cd /root/GolandProjects/pulumi-avx-test-dummy && node demo_complete_typescript.js'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: pulumi-aviatrix-complete-coverage-test
        name: Pulumi Aviatrix Complete Coverage Test (100% Feature Coverage)
        entry: bash -c 'cd /root/GolandProjects/pulumi-avx-test-dummy && ./validate_complete_coverage.sh'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
